### ISSUE TITLE
TODO: Project Proposal

### ISSUE THREAD

**Issue by callahantiff** [henrylittle21/SRS-NLP#4]
@henrylittle21 @lajohnson02 @jackstolt  - Can you send me some example proposals we can use to start drafting your project proposal?

**Comment by henrylittle21** [comment]
[Final+Paper+Draft+Ducey+and+Clemenson.docx](https://github.com/henrylittle21/SRS-NLP/files/3785483/Final%2BPaper%2BDraft%2BDucey%2Band%2BClemenson.docx)
[Final+paper+Will+Cordell.docx](https://github.com/henrylittle21/SRS-NLP/files/3785484/Final%2Bpaper%2BWill%2BCordell.docx)
[SRS+Final+Paper+Paswaters+and+Gooding-Lord.docx](https://github.com/henrylittle21/SRS-NLP/files/3785485/SRS%2BFinal%2BPaper%2BPaswaters%2Band%2BGooding-Lord.docx)
[Cai.pdf](https://github.com/henrylittle21/SRS-NLP/files/3785486/Cai.pdf)

**Comment by callahantiff** [comment]
I want to confirm the date and time for our meeting Sunday. Can you please confirm the following?:
- [x] Where you would like to meet?  
- [x] Are we still meeting at 12pm?

**Comment by jackstolt** [comment]
@callahantiff Do you want to meet us at the same cafe? That worked last time. Would 10:30 am work for you? I would prefer that time.

**Comment by jackstolt** [comment]
> I want to confirm the date and time for our meeting Sunday. Can you please confirm the following?:
> 
> * [ ]  Where you would like to meet?
> * [ ]  Are we still meeting at 12pm?

**Comment by callahantiff** [comment]
> @callahantiff Do you want to meet us at the same cafe? That worked last time. Would 10:30 am work for you? I would prefer that time.

Yep, I rearranged some things and can be available 10:30am-12pm tomorrow. I can also meet you guys at the same cafe. 

For tomorrow, I'd like us to first focus on creating an outline of the proposal so that once I leave you guys have what you need to start drafting the proposal. If we have time to talk about data collection and the tutorials, that will be great. If not, we will set-up another time to meet next week. Sound good?

**Comment by jackstolt** [comment]
@callahantiff I like the sound of that plan. The proposal is definitely priority number one. An outline is essential and then we can take the bulk of the writing from there.

**Comment by callahantiff** [comment]
The Google Doc draft of the proposal can be accessed [here](https://docs.google.com/document/d/1bBMmCjz4wgi2wJKHZweCITj6wvj4_CIVeOiFI2KLxII/edit#heading=h.cm72ghulok3x).

**Comment by callahantiff** [comment]
What time and where would you guys like to meet tomorrow?

**Comment by jackstolt** [comment]
@callahantiff 12:15 is the earliest and therefore the best time we can meet. We can go as long as you like from that point. As far as location, we were hoping we could get a quiet space with a whiteboard maybe? I know the Louisville Library is an option. Norlins would work too if you could get a room.

**Comment by callahantiff** [comment]
> @callahantiff 12:15 is the earliest and therefore the best time we can meet. We can go as long as you like from that point. As far as location, we were hoping we could get a quiet space with a whiteboard maybe? I know the Louisville Library is an option. Norlins would work too if you could get a room.

OK, sounds good. Let's meet at the Louisville Library. I can be there at 1pm. Sound good?

**Comment by jackstolt** [comment]
@callahantiff That works! See you then.

**Comment by lajohnson02** [comment]
Hey Tiffany, I think that we are mostly done with the paper if you want to
look over it now. Thanks

**Comment by henrylittle21** [comment]
@callahantiff Let us know when you have done a read-through of our paper so we can fix anything before it is due today at 4 pm! You rock!

**Comment by callahantiff** [comment]
> @callahantiff Let us know when you have done a read-through of our paper so we can fix anything before it is due today at 4 pm! You rock!

OK, read through done! Nice job guys! I left two comments. Please read and address them. Assuming those are resolved, then I think you are good to go!

**Comment by callahantiff** [comment]
Draft is complete and has been turned in! 🎉 🥇 😄 

I am going to close this issue now. Re-open it when you get feedback from your teacher.
